# These are supported funding model platforms

GitHub: ['https://github.com/sponsors/bulsionyking']
cashapp: ['http://cashapp.app/$juliusthejules']
paypal: ['https://paypal.me/juliusthejules88']
paylinkz: ['https://paylinkz.app/juliusthejules']
